name: Org Terraform Docs
on:
    pull_request:
    workflow_call:

jobs:
  terraform-docs:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-docs.yml@08aba95a48c6a65df82d3bbbfe9770de37ead95b # v0.9.0