name: Org Release

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-release.yml@08aba95a48c6a65df82d3bbbfe9770de37ead95b # v0.9.0
    secrets: inherit
